"""rename image field

Revision ID: ab94844f91ed
Revises: fb881fe4d8e4
Create Date: 2023-11-04 19:36:43.576499

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab94844f91ed'
down_revision: Union[str, None] = 'fb881fe4d8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'example_of_work',
        sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column('example_of_work', 'main_photo')
    op.add_column(
        'example_photo',
        sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column('example_photo', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'example_photo',
        sa.Column('path', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column('example_photo', 'image')
    op.add_column(
        'example_of_work',
        sa.Column('main_photo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column('example_of_work', 'image')
    # ### end Alembic commands ###
