"""add user and token

Revision ID: f3ef26dc9633
Revises: ab94844f91ed
Create Date: 2023-11-12 00:18:15.609156

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3ef26dc9633'
down_revision: Union[str, None] = 'ab94844f91ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'auth_token',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('exp_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['admin_user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.alter_column(
        'example_of_work',
        'image',
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column('example_photo', 'image', existing_type=sa.VARCHAR(length=200), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('example_photo', 'image', existing_type=sa.VARCHAR(length=200), nullable=True)
    op.alter_column('example_of_work', 'image', existing_type=sa.VARCHAR(length=200), nullable=True)
    op.drop_table('auth_token')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
